// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniRedditCloneApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace MiniRedditCloneApi.Migrations
{
    [DbContext(typeof(MiniRedditCloneApiDbContext))]
    [Migration("20251204193101_AddRolePromotionsAndDemotions")]
    partial class AddRolePromotionsAndDemotions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DomainHerd", b =>
                {
                    b.Property<int>("DomainsId")
                        .HasColumnType("integer");

                    b.Property<int>("HerdsId")
                        .HasColumnType("integer");

                    b.HasKey("DomainsId", "HerdsId");

                    b.HasIndex("HerdsId");

                    b.ToTable("DomainHerd");
                });

            modelBuilder.Entity("InsightTopic", b =>
                {
                    b.Property<int>("InsightsId")
                        .HasColumnType("integer");

                    b.Property<int>("TopicsId")
                        .HasColumnType("integer");

                    b.HasKey("InsightsId", "TopicsId");

                    b.HasIndex("TopicsId");

                    b.ToTable("InsightTopic");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("domains", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsSystem = true,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 2,
                            IsSystem = true,
                            Name = "Technology & Computing"
                        },
                        new
                        {
                            Id = 3,
                            IsSystem = true,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 4,
                            IsSystem = true,
                            Name = "Arts & Literature"
                        },
                        new
                        {
                            Id = 5,
                            IsSystem = true,
                            Name = "Culture & Humanities"
                        },
                        new
                        {
                            Id = 6,
                            IsSystem = true,
                            Name = "Gaming & Entertainment"
                        },
                        new
                        {
                            Id = 7,
                            IsSystem = true,
                            Name = "Space & Astronomy"
                        },
                        new
                        {
                            Id = 8,
                            IsSystem = true,
                            Name = "Engineering & Making"
                        });
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Herd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowNSFW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_nsfw");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Name" });

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("herds", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.HerdNerd", b =>
                {
                    b.Property<string>("NerdId")
                        .HasColumnType("text")
                        .HasColumnName("nerd_id");

                    b.Property<int>("HerdId")
                        .HasColumnType("integer")
                        .HasColumnName("herd_id");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("role");

                    b.HasKey("NerdId", "HerdId");

                    b.HasIndex("HerdId", "Role");

                    b.ToTable("herd_nerds", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Insight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("HerdId")
                        .HasColumnType("integer")
                        .HasColumnName("herd_id");

                    b.Property<bool>("IsNSFW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_nsfw");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text")
                        .HasColumnName("media_url");

                    b.Property<string>("NerdId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nerd_id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("HerdId");

                    b.HasIndex("NerdId");

                    b.ToTable("insights", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.InsightReaction", b =>
                {
                    b.Property<int>("InsightId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<string>("NerdId")
                        .HasColumnType("text")
                        .HasColumnName("nerd_id");

                    b.Property<DateTime>("ReactedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reacted_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Reaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reaction");

                    b.HasKey("InsightId", "NerdId");

                    b.HasIndex("NerdId");

                    b.HasIndex("InsightId", "Reaction");

                    b.ToTable("insight_reactions", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Nerd", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("AvatarType")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DefaultAvatarNum")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "UserName" });

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("UploadedAvatar")
                        .HasColumnType("bytea");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("nerds", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CommentedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("commented_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("InsightId")
                        .HasColumnType("integer")
                        .HasColumnName("insight_id");

                    b.Property<string>("NerdId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nerd_id");

                    b.HasKey("Id");

                    b.HasIndex("InsightId");

                    b.HasIndex("NerdId");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.NoteReaction", b =>
                {
                    b.Property<int>("NoteId")
                        .HasColumnType("integer")
                        .HasColumnName("post_comment_id");

                    b.Property<string>("NerdId")
                        .HasColumnType("text")
                        .HasColumnName("nerd_id");

                    b.Property<DateTime>("ReactedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reacted_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Reaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reaction");

                    b.HasKey("NoteId", "NerdId");

                    b.HasIndex("NerdId");

                    b.HasIndex("NoteId", "Reaction");

                    b.ToTable("note_reactions", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.RoleDemotion", b =>
                {
                    b.Property<string>("NerdId")
                        .HasColumnType("text")
                        .HasColumnName("nerd_id");

                    b.Property<int>("HerdId")
                        .HasColumnType("integer")
                        .HasColumnName("herd_id");

                    b.Property<string>("ModeratorId")
                        .HasColumnType("text")
                        .HasColumnName("moderator_id");

                    b.HasKey("NerdId", "HerdId", "ModeratorId");

                    b.HasIndex("ModeratorId");

                    b.ToTable("role_demotions", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.RolePromotion", b =>
                {
                    b.Property<string>("NerdId")
                        .HasColumnType("text")
                        .HasColumnName("nerd_id");

                    b.Property<int>("HerdId")
                        .HasColumnType("integer")
                        .HasColumnName("herd_id");

                    b.Property<string>("ModeratorId")
                        .HasColumnType("text")
                        .HasColumnName("moderator_id");

                    b.HasKey("NerdId", "HerdId", "ModeratorId");

                    b.HasIndex("ModeratorId");

                    b.ToTable("role_promotions", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DomainId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("DomainId", "Name")
                        .IsUnique();

                    b.ToTable("topics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DomainId = 1,
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 2,
                            DomainId = 1,
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 3,
                            DomainId = 1,
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 4,
                            DomainId = 1,
                            Name = "Earth Science"
                        },
                        new
                        {
                            Id = 5,
                            DomainId = 1,
                            Name = "Environmental Science"
                        },
                        new
                        {
                            Id = 6,
                            DomainId = 1,
                            Name = "Neuroscience"
                        },
                        new
                        {
                            Id = 7,
                            DomainId = 1,
                            Name = "Psychology"
                        },
                        new
                        {
                            Id = 8,
                            DomainId = 1,
                            Name = "Anthropology"
                        },
                        new
                        {
                            Id = 9,
                            DomainId = 1,
                            Name = "Ecology"
                        },
                        new
                        {
                            Id = 10,
                            DomainId = 1,
                            Name = "Zoology"
                        },
                        new
                        {
                            Id = 11,
                            DomainId = 1,
                            Name = "Genetics"
                        },
                        new
                        {
                            Id = 12,
                            DomainId = 1,
                            Name = "Medicine"
                        },
                        new
                        {
                            Id = 13,
                            DomainId = 1,
                            Name = "General"
                        },
                        new
                        {
                            Id = 14,
                            DomainId = 2,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 15,
                            DomainId = 2,
                            Name = "Algorithms"
                        },
                        new
                        {
                            Id = 16,
                            DomainId = 2,
                            Name = "Data Structures"
                        },
                        new
                        {
                            Id = 17,
                            DomainId = 2,
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 18,
                            DomainId = 2,
                            Name = "Mobile Development"
                        },
                        new
                        {
                            Id = 19,
                            DomainId = 5,
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = 20,
                            DomainId = 2,
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = 21,
                            DomainId = 2,
                            Name = "Databases"
                        },
                        new
                        {
                            Id = 22,
                            DomainId = 2,
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = 23,
                            DomainId = 2,
                            Name = "AI & Machine Learning"
                        },
                        new
                        {
                            Id = 24,
                            DomainId = 2,
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = 25,
                            DomainId = 2,
                            Name = "System Design"
                        },
                        new
                        {
                            Id = 26,
                            DomainId = 2,
                            Name = "Networking"
                        },
                        new
                        {
                            Id = 27,
                            DomainId = 2,
                            Name = "General"
                        },
                        new
                        {
                            Id = 28,
                            DomainId = 3,
                            Name = "Algebra"
                        },
                        new
                        {
                            Id = 29,
                            DomainId = 3,
                            Name = "Calculus"
                        },
                        new
                        {
                            Id = 30,
                            DomainId = 3,
                            Name = "Geometry"
                        },
                        new
                        {
                            Id = 31,
                            DomainId = 3,
                            Name = "Statistics"
                        },
                        new
                        {
                            Id = 32,
                            DomainId = 3,
                            Name = "Probability"
                        },
                        new
                        {
                            Id = 33,
                            DomainId = 3,
                            Name = "Number Theory"
                        },
                        new
                        {
                            Id = 34,
                            DomainId = 3,
                            Name = "Linear Algebra"
                        },
                        new
                        {
                            Id = 35,
                            DomainId = 3,
                            Name = "Discrete Math"
                        },
                        new
                        {
                            Id = 36,
                            DomainId = 3,
                            Name = "Mathematical Logic"
                        },
                        new
                        {
                            Id = 37,
                            DomainId = 3,
                            Name = "Topology"
                        },
                        new
                        {
                            Id = 38,
                            DomainId = 3,
                            Name = "General"
                        },
                        new
                        {
                            Id = 39,
                            DomainId = 4,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 40,
                            DomainId = 4,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 41,
                            DomainId = 4,
                            Name = "Poetry"
                        },
                        new
                        {
                            Id = 42,
                            DomainId = 4,
                            Name = "Visual Arts"
                        },
                        new
                        {
                            Id = 43,
                            DomainId = 4,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 44,
                            DomainId = 4,
                            Name = "Film Analysis"
                        },
                        new
                        {
                            Id = 45,
                            DomainId = 4,
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 46,
                            DomainId = 4,
                            Name = "Creative Writing"
                        },
                        new
                        {
                            Id = 47,
                            DomainId = 4,
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = 48,
                            DomainId = 4,
                            Name = "History of Art"
                        },
                        new
                        {
                            Id = 49,
                            DomainId = 4,
                            Name = "General"
                        },
                        new
                        {
                            Id = 50,
                            DomainId = 5,
                            Name = "Linguistics"
                        },
                        new
                        {
                            Id = 51,
                            DomainId = 5,
                            Name = "History"
                        },
                        new
                        {
                            Id = 52,
                            DomainId = 5,
                            Name = "Sociology"
                        },
                        new
                        {
                            Id = 53,
                            DomainId = 5,
                            Name = "World Cultures"
                        },
                        new
                        {
                            Id = 54,
                            DomainId = 5,
                            Name = "Religion"
                        },
                        new
                        {
                            Id = 55,
                            DomainId = 5,
                            Name = "Mythology"
                        },
                        new
                        {
                            Id = 56,
                            DomainId = 5,
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 57,
                            DomainId = 5,
                            Name = "Ethics"
                        },
                        new
                        {
                            Id = 58,
                            DomainId = 5,
                            Name = "Economics"
                        },
                        new
                        {
                            Id = 59,
                            DomainId = 5,
                            Name = "General"
                        },
                        new
                        {
                            Id = 60,
                            DomainId = 6,
                            Name = "Video Games"
                        },
                        new
                        {
                            Id = 61,
                            DomainId = 6,
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = 62,
                            DomainId = 6,
                            Name = "Board Games"
                        },
                        new
                        {
                            Id = 63,
                            DomainId = 6,
                            Name = "Anime"
                        },
                        new
                        {
                            Id = 64,
                            DomainId = 6,
                            Name = "Comics"
                        },
                        new
                        {
                            Id = 65,
                            DomainId = 6,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 66,
                            DomainId = 6,
                            Name = "TV Shows"
                        },
                        new
                        {
                            Id = 67,
                            DomainId = 6,
                            Name = "Esports"
                        },
                        new
                        {
                            Id = 68,
                            DomainId = 6,
                            Name = "Tabletop RPGs"
                        },
                        new
                        {
                            Id = 69,
                            DomainId = 6,
                            Name = "Digital RPGs"
                        },
                        new
                        {
                            Id = 70,
                            DomainId = 6,
                            Name = "General"
                        },
                        new
                        {
                            Id = 71,
                            DomainId = 7,
                            Name = "Astrophysics"
                        },
                        new
                        {
                            Id = 72,
                            DomainId = 7,
                            Name = "Cosmology"
                        },
                        new
                        {
                            Id = 73,
                            DomainId = 7,
                            Name = "Space Exploration"
                        },
                        new
                        {
                            Id = 74,
                            DomainId = 7,
                            Name = "Telescopes"
                        },
                        new
                        {
                            Id = 75,
                            DomainId = 7,
                            Name = "Planetary Science"
                        },
                        new
                        {
                            Id = 76,
                            DomainId = 7,
                            Name = "Black Holes"
                        },
                        new
                        {
                            Id = 77,
                            DomainId = 7,
                            Name = "Astrobiology"
                        },
                        new
                        {
                            Id = 78,
                            DomainId = 7,
                            Name = "Star Formation"
                        },
                        new
                        {
                            Id = 79,
                            DomainId = 7,
                            Name = "General"
                        },
                        new
                        {
                            Id = 80,
                            DomainId = 8,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 81,
                            DomainId = 8,
                            Name = "Robotics"
                        },
                        new
                        {
                            Id = 82,
                            DomainId = 8,
                            Name = "Mechanical Engineering"
                        },
                        new
                        {
                            Id = 83,
                            DomainId = 8,
                            Name = "Electrical Engineering"
                        },
                        new
                        {
                            Id = 84,
                            DomainId = 8,
                            Name = "Civil Engineering"
                        },
                        new
                        {
                            Id = 85,
                            DomainId = 8,
                            Name = "3D Printing"
                        },
                        new
                        {
                            Id = 86,
                            DomainId = 8,
                            Name = "DIY Projects"
                        },
                        new
                        {
                            Id = 87,
                            DomainId = 8,
                            Name = "Hardware Hacking"
                        });
                });

            modelBuilder.Entity("DomainHerd", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Domain", null)
                        .WithMany()
                        .HasForeignKey("DomainsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.Herd", null)
                        .WithMany()
                        .HasForeignKey("HerdsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InsightTopic", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Insight", null)
                        .WithMany()
                        .HasForeignKey("InsightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Nerd", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Nerd", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.Nerd", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Nerd", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.HerdNerd", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Herd", "Herd")
                        .WithMany("HerdNerds")
                        .HasForeignKey("HerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.Nerd", "Nerd")
                        .WithMany("HerdNerds")
                        .HasForeignKey("NerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herd");

                    b.Navigation("Nerd");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Insight", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Herd", "Herd")
                        .WithMany("Insights")
                        .HasForeignKey("HerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.Nerd", "Nerd")
                        .WithMany("Insights")
                        .HasForeignKey("NerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herd");

                    b.Navigation("Nerd");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.InsightReaction", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Insight", "Insight")
                        .WithMany("InsightReactions")
                        .HasForeignKey("InsightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.Nerd", "Nerd")
                        .WithMany("InsightReactions")
                        .HasForeignKey("NerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insight");

                    b.Navigation("Nerd");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Note", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Insight", "Insight")
                        .WithMany("Notes")
                        .HasForeignKey("InsightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.Nerd", "Nerd")
                        .WithMany("Notes")
                        .HasForeignKey("NerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insight");

                    b.Navigation("Nerd");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.NoteReaction", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Nerd", "Nerd")
                        .WithMany("NoteReactions")
                        .HasForeignKey("NerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.Note", "Note")
                        .WithMany("NoteReactions")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nerd");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.RoleDemotion", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Nerd", "Moderator")
                        .WithMany("RoleDemotions")
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.HerdNerd", "HerdNerd")
                        .WithMany("RoleDemotions")
                        .HasForeignKey("NerdId", "HerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HerdNerd");

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.RolePromotion", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Nerd", "Moderator")
                        .WithMany("RolePromotions")
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.HerdNerd", "HerdNerd")
                        .WithMany("RolePromotions")
                        .HasForeignKey("NerdId", "HerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HerdNerd");

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Topic", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Domain", "Domain")
                        .WithMany("Topics")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Domain", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Herd", b =>
                {
                    b.Navigation("HerdNerds");

                    b.Navigation("Insights");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.HerdNerd", b =>
                {
                    b.Navigation("RoleDemotions");

                    b.Navigation("RolePromotions");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Insight", b =>
                {
                    b.Navigation("InsightReactions");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Nerd", b =>
                {
                    b.Navigation("HerdNerds");

                    b.Navigation("InsightReactions");

                    b.Navigation("Insights");

                    b.Navigation("NoteReactions");

                    b.Navigation("Notes");

                    b.Navigation("RoleDemotions");

                    b.Navigation("RolePromotions");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Note", b =>
                {
                    b.Navigation("NoteReactions");
                });
#pragma warning restore 612, 618
        }
    }
}
# File update Fri, Jan  9, 2026  9:16:09 PM
# Update Fri, Jan  9, 2026  9:25:49 PM
# Update Fri, Jan  9, 2026  9:34:33 PM
