// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniRedditCloneApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniRedditCloneApi.Migrations
{
    [DbContext(typeof(MiniRedditCloneApiDbContext))]
    [Migration("20251202191129_AddAvatarSupport")]
    partial class AddAvatarSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Herd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowNSFW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_nsfw");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("herds", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.HerdNerd", b =>
                {
                    b.Property<string>("NerdId")
                        .HasColumnType("text")
                        .HasColumnName("nerd_id");

                    b.Property<int>("HerdId")
                        .HasColumnType("integer")
                        .HasColumnName("herd_id");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("role");

                    b.HasKey("NerdId", "HerdId");

                    b.HasIndex("HerdId", "Role");

                    b.ToTable("herd_nerds", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Insight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("HerdId")
                        .HasColumnType("integer")
                        .HasColumnName("herd_id");

                    b.Property<bool>("IsNSFW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_nsfw");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text")
                        .HasColumnName("media_url");

                    b.Property<string>("NerdId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nerd_id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("HerdId");

                    b.HasIndex("NerdId");

                    b.ToTable("insights", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.InsightReaction", b =>
                {
                    b.Property<int>("InsightId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<string>("NerdId")
                        .HasColumnType("text")
                        .HasColumnName("nerd_id");

                    b.Property<DateTime>("ReactedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reacted_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Reaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reaction");

                    b.HasKey("InsightId", "NerdId");

                    b.HasIndex("NerdId");

                    b.HasIndex("InsightId", "Reaction");

                    b.ToTable("insight_reactions", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Nerd", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("AvatarType")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DefaultAvatarNum")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("UploadedAvatar")
                        .HasColumnType("bytea");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("nerds", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CommentedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("commented_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("InsightId")
                        .HasColumnType("integer")
                        .HasColumnName("insight_id");

                    b.Property<string>("NerdId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nerd_id");

                    b.HasKey("Id");

                    b.HasIndex("InsightId");

                    b.HasIndex("NerdId");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.NoteReaction", b =>
                {
                    b.Property<int>("NoteId")
                        .HasColumnType("integer")
                        .HasColumnName("post_comment_id");

                    b.Property<string>("NerdId")
                        .HasColumnType("text")
                        .HasColumnName("nerd_id");

                    b.Property<DateTime>("ReactedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reacted_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Reaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reaction");

                    b.HasKey("NoteId", "NerdId");

                    b.HasIndex("NerdId");

                    b.HasIndex("NoteId", "Reaction");

                    b.ToTable("note_reactions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Nerd", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Nerd", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.Nerd", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Nerd", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.HerdNerd", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Herd", "Herd")
                        .WithMany("HerdNerds")
                        .HasForeignKey("HerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.Nerd", "Nerd")
                        .WithMany("HerdNerds")
                        .HasForeignKey("NerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herd");

                    b.Navigation("Nerd");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Insight", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Herd", "Herd")
                        .WithMany("Insights")
                        .HasForeignKey("HerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.Nerd", "Nerd")
                        .WithMany("Insights")
                        .HasForeignKey("NerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herd");

                    b.Navigation("Nerd");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.InsightReaction", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Insight", "Insight")
                        .WithMany("InsightReactions")
                        .HasForeignKey("InsightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.Nerd", "Nerd")
                        .WithMany("InsightReactions")
                        .HasForeignKey("NerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insight");

                    b.Navigation("Nerd");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Note", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Insight", "Insight")
                        .WithMany("Notes")
                        .HasForeignKey("InsightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.Nerd", "Nerd")
                        .WithMany("Notes")
                        .HasForeignKey("NerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insight");

                    b.Navigation("Nerd");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.NoteReaction", b =>
                {
                    b.HasOne("MiniRedditCloneApi.Models.Nerd", "Nerd")
                        .WithMany("NoteReactions")
                        .HasForeignKey("NerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniRedditCloneApi.Models.Note", "Note")
                        .WithMany("NoteReactions")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nerd");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Herd", b =>
                {
                    b.Navigation("HerdNerds");

                    b.Navigation("Insights");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Insight", b =>
                {
                    b.Navigation("InsightReactions");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Nerd", b =>
                {
                    b.Navigation("HerdNerds");

                    b.Navigation("InsightReactions");

                    b.Navigation("Insights");

                    b.Navigation("NoteReactions");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("MiniRedditCloneApi.Models.Note", b =>
                {
                    b.Navigation("NoteReactions");
                });
#pragma warning restore 612, 618
        }
    }
}
# File update Fri, Jan  9, 2026  9:16:07 PM
# Update Fri, Jan  9, 2026  9:25:47 PM
# Update Fri, Jan  9, 2026  9:34:32 PM
// Logic update: qCYPIaXPBCtP
// Logic update: rPLzWjeFjB4y
// Logic update: QFCauuhUE0il
// Logic update: zLTugoAgQEMs
// Logic update: je7xFzCuZzAl
// Logic update: jLiq3rBPyiQv
// Logic update: pHJDeJxWVkDI
